#!/bin/bash
# Counts keyword occurrences

LOGFILE=$1
KEYWORD=${2:-error}
COUNT=0

while read LINE; do
    if echo "$LINE" | grep -iq "$KEYWORD"; then
        COUNT=$((COUNT+1))
    fi
done < $LOGFILE

echo "Keyword '$KEYWORD' found $COUNT times"
